services:
  postgres:
    image: postgres:16-alpine
    container_name: next-auth-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: next-auth
    volumes:
      - ./db-data:/var/lib/postgresql/data
